version: '3.8'

services:
  pet-dashboard:
    image: kleekr/pws-extra-tools:1.0
    container_name: pet-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
